import Head from 'next/head';

export default function BootcampTestimonialsSlider() {
  return (
    <>
      <Head>
        <title>Frontend Mentor Challenges</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-screen h-screen flex justify-center items-center'>
        <h1 className='font-bold text-9xl text-red-600'>Project 1</h1>
      </main>
    </>
  );
}
